import Head from 'next/head'
import { Inter } from 'next/font/google'
import Hero from '@/components/hero'
import Exchanges from '@/components/exchanges'
import Partners from '@/components/partners'
import Watchlist from '@/components/watchlist'
import NFT from '@/components/NFT'
import Security from '@/components/security'
import Getstarted from '@/components/getstarted'
import FAQ from '@/components/FAQ'
import { useSession } from "next-auth/react"
import Crypto from '@components/Crypto'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const {data:session} = useSession()

  return (
    <>
      <Head>
        <title>Crypto Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {session ? User({session}) : Guest()}
    </>
  )
}

//Guest
function Guest() {
  return (
    <main>
        <Hero />
        <Crypto />
        <Exchanges />
        <Partners />
        <Watchlist />
        <NFT />
        <Security />
        <Getstarted />
        <FAQ />
      </main>
  )
}

//authorised user
function User({session}) {
  return (
    <main>
        <Hero />
        <Crypto />
        <Exchanges />
        <Partners />
        <Watchlist />
        <NFT />
        <Security />
        <Getstarted />
        <FAQ />
      </main>
  )
}
